//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CnpcBlockly.Generator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Snippets {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Snippets() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CnpcBlockly.Generator.Resources.Snippets", typeof(Snippets).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        /// * @license
        /// * Copyright 2024 Cryville
        /// * SPDX-License-Identifier: Apache-2.0
        /// */.
        /// </summary>
        internal static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&apos;kind&apos;:&apos;category&apos;,&apos;name&apos;:&apos;Logic&apos;,&apos;categorystyle&apos;:&apos;logic_category&apos;,&apos;contents&apos;:[{&apos;kind&apos;:&apos;block&apos;,&apos;type&apos;:&apos;controls_if&apos;,},{&apos;kind&apos;:&apos;block&apos;,&apos;type&apos;:&apos;logic_compare&apos;,},{&apos;kind&apos;:&apos;block&apos;,&apos;type&apos;:&apos;logic_operation&apos;,},{&apos;kind&apos;:&apos;block&apos;,&apos;type&apos;:&apos;logic_negate&apos;,},{&apos;kind&apos;:&apos;block&apos;,&apos;type&apos;:&apos;logic_boolean&apos;,},{&apos;kind&apos;:&apos;block&apos;,&apos;type&apos;:&apos;logic_null&apos;,},{&apos;kind&apos;:&apos;block&apos;,&apos;type&apos;:&apos;logic_ternary&apos;,},],},{&apos;kind&apos;:&apos;category&apos;,&apos;name&apos;:&apos;Loops&apos;,&apos;categorystyle&apos;:&apos;loop_category&apos;,&apos;contents&apos;:[{&apos;kind&apos;:&apos;block&apos;,&apos;type&apos;:&apos;controls_repeat_ext&apos;,&apos;inputs&apos;:{&apos;TIMES&apos;:{&apos;sha [rest of string was tru....
        /// </summary>
        internal static string ToolboxBuiltin {
            get {
                return ResourceManager.GetString("ToolboxBuiltin", resourceCulture);
            }
        }
    }
}
