//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CnpcBlockly.Generator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CnpcBlockly.Generator.Resources.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;EOF&gt;.
        /// </summary>
        internal static string EOF {
            get {
                return ResourceManager.GetString("EOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or unsupported API format..
        /// </summary>
        internal static string Error_ApiFormat {
            get {
                return ResourceManager.GetString("Error_ApiFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory not found..
        /// </summary>
        internal static string Error_DirectoryNotFound {
            get {
                return ResourceManager.GetString("Error_DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found..
        /// </summary>
        internal static string Error_FileNotFound {
            get {
                return ResourceManager.GetString("Error_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type..
        /// </summary>
        internal static string Error_InvalidType {
            get {
                return ResourceManager.GetString("Error_InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type reference..
        /// </summary>
        internal static string Error_InvalidTypeReference {
            get {
                return ResourceManager.GetString("Error_InvalidTypeReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base object type not found..
        /// </summary>
        internal static string Error_MissingBaseType {
            get {
                return ResourceManager.GetString("Error_MissingBaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input the path to CustomNPCsAPI: .
        /// </summary>
        internal static string Prompt_InputApiPath {
            get {
                return ResourceManager.GetString("Prompt_InputApiPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        internal static string Punc_Colon {
            get {
                return ResourceManager.GetString("Punc_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot;.
        /// </summary>
        internal static string Punc_Quote {
            get {
                return ResourceManager.GetString("Punc_Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;.
        /// </summary>
        internal static string Punc_QuoteAlt {
            get {
                return ResourceManager.GetString("Punc_QuoteAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error at line {0}, position {1}.
        /// </summary>
        internal static string TokenizerError {
            get {
                return ResourceManager.GetString("TokenizerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected {0}, got {1}..
        /// </summary>
        internal static string TokenizerError_RequireSymbol {
            get {
                return ResourceManager.GetString("TokenizerError_RequireSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignoring the element type of the array type {0}..
        /// </summary>
        internal static string Warning_ArrayType {
            get {
                return ResourceManager.GetString("Warning_ArrayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignoring the type parameters of the generic type {0}..
        /// </summary>
        internal static string Warning_GenericType {
            get {
                return ResourceManager.GetString("Warning_GenericType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown type {0}..
        /// </summary>
        internal static string Warning_UnknownType {
            get {
                return ResourceManager.GetString("Warning_UnknownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreferenced type {0}..
        /// </summary>
        internal static string Warning_UnreferencedType {
            get {
                return ResourceManager.GetString("Warning_UnreferencedType", resourceCulture);
            }
        }
    }
}
