name: Build Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:
  
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout API
        uses: actions/checkout@v4
        with:
          repository: PopSlime/CustomNPCsAPI
          ref: javadoc
          path: CustomNPCsAPI
      - name: Setup .NET 8.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x
      - name: Install NPM Dependencies
        run: npm install
      - name: Build Editor
        run: make
        env:
          CNPC_API_DIR: CustomNPCsAPI
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: Editor/dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
